### ISSUE TITLE
There seems to be something wrong with the code

### ISSUE THREAD

**Issue by dhhcj1** [laisimiao/classification-cifar10-pytorch#1]
Traceback (most recent call last):
  File "main.py", line 15, in <module>
    from utils import progress_bar
  File "D:\classification-cifar10-pytorch-master\utils.py", line 45, in <module>
    _, term_width = os.popen('stty size', 'r').read().split()
ValueError: not enough values to unpack (expected 2, got 0)

**Comment by laisimiao** [comment]
run this:python main.py --resume --lr 0.1 --trainbs 128 --testbs 100 in your terminal, not in IDE like pycharm, then it will be ok.

**Comment by liguilan1227** [comment]
Is the checkpoint neccessary to train the net? When I run it, the error occured: Traceback (most recent call last):
  File "main.py", line 77, in <module>
    assert os.path.isdir('checkpoint'), 'Error: no checkpoint directory found!'
AssertionError: Error: no checkpoint directory found!
